easy_admin:
    site_name: 'Diane Langues Admin'
    user:
        name_property_path: false
        display_avatar: false
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@A2lixTranslationForm/bootstrap_4_layout.html.twig'
        brand_color: '#1ABC9C'
    entities:
        WebsiteConfig:
            class: App\Entity\WebsiteConfig
            disabled_actions: ['new']
        PortFolio:
            class: App\Entity\PortFolio
            list:
                fields:
                    - projectName
                    - description
                    - { property: "date", type: "date"}
                    - client
                    - category
                    - { property: 'image', type: 'image', base_path: '%app.path.portFolio_images%' }
            show:
                fields:
                    - projectName
                    - description
                    - { property: "date", type: "date"}
                    - client
                    - category
                    - { property: 'image', type: 'image', base_path: '%app.path.portFolio_images%' }
            form:
                fields:
                    - projectName
                    - { property: "date", type: "date"}
                    - client
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType }
                    - { property: 'imageFile', type: 'vich_image' }
        Domain:
            class: App\Entity\Domain
            list:
                fields:
                    - type
                    - description
                    - { property: 'image', type: 'image', base_path: '%app.path.domain_images%' }
            show:
                fields:
                    - type
                    - description
                    - { property: 'image', type: 'image', base_path: '%app.path.domain_images%' }
            form:
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType }
                    - { property: 'imageFile', type: 'vich_image' }
        # Reference:
        #     class: App\Entity\Reference
        Service:
            class: App\Entity\Service
            list:
                fields:
                    - type
                    - description
                    - price
                    - { property: 'image', type: 'image', base_path: '%app.path.service_images%' }
            show:
                fields:
                    - type
                    - description
                    - price
                    - { property: 'image', type: 'image', base_path: '%app.path.service_images%' }
            form:
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType }
                    - { property: 'imageFile', type: 'vich_image' }
        About:
            class: App\Entity\About
            list:
                fields:
                    - date
                    - title
                    - description
                    - { property: 'image', type: 'image', base_path: '%app.path.about_images%' }
            show:
                fields:
                    - date
                    - title
                    - description
                    - { property: 'image', type: 'image', base_path: '%app.path.about_images%' }
            form:
                fields:
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType }
                    - date
                    - { property: 'imageFile', type: 'vich_image' }