easy_admin:
    site_name: 'Diane Langues Admin'
    user:
        display_name: true
        display_avatar: false
    entities:
        Contact:
            class: App\Entity\Contact
        Domain:
            class: App\Entity\Domain
        Reference:
            class: App\Entity\Reference
        Service:
            class: App\Entity\Service
